#!/bin/bash
myip=`ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0' | head -n1`;

flag=0

echo

function create_user() {
	useradd -M $uname
	echo "$uname:$pass" | chpasswd
	usermod -e $expdate $uname

	myip=`ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0' | head -n1`;
	myip2="s/xxxxxxxxx/$myip/g";	
	wget -qO /tmp/client.ovpn "http://zakidotmy.5gbfree.com/debian32/1194-client.conf"
	sed -i 's/remote xxxxxxxxx 1194/remote xxxxxxxxx 443/g' /tmp/client.ovpn
	sed -i $myip2 /tmp/client.ovpn
	echo ""
	echo "OpenVPN  : TCP 443 (client config : http://$myip:81/client.tar)"
}

function renew_user() {
	echo "New expiration date for $uname: $expdate...";
	usermod -e $expdate $uname
}

function delete_user(){
	userdel $uname
}

function expired_users(){
	cat /etc/shadow | cut -d: -f1,8 | sed /:$/d > /tmp/expirelist.txt
	totalaccounts=`cat /tmp/expirelist.txt | wc -l`
	for((i=1; i<=$totalaccounts; i++ )); do
		tuserval=`head -n $i /tmp/expirelist.txt | tail -n 1`
		username=`echo $tuserval | cut -f1 -d:`
		userexp=`echo $tuserval | cut -f2 -d:`
		userexpireinseconds=$(( $userexp * 86400 ))
		todaystime=`date +%s`
		if [ $userexpireinseconds -lt $todaystime ] ; then
			echo $username
		fi
	done
	rm /tmp/expirelist.txt
}

function not_expired_users(){
    cat /etc/shadow | cut -d: -f1,8 | sed /:$/d > /tmp/expirelist.txt
    totalaccounts=`cat /tmp/expirelist.txt | wc -l`
    for((i=1; i<=$totalaccounts; i++ )); do
        tuserval=`head -n $i /tmp/expirelist.txt | tail -n 1`
        username=`echo $tuserval | cut -f1 -d:`
        userexp=`echo $tuserval | cut -f2 -d:`
        userexpireinseconds=$(( $userexp * 86400 ))
        todaystime=`date +%s`
        if [ $userexpireinseconds -gt $todaystime ] ; then
            echo $username
        fi
    done
	rm /tmp/expirelist.txt
}

function used_data(){
	myip=`ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0' | head -n1`
	myint=`ifconfig | grep -B1 "inet addr:$myip" | head -n1 | awk '{print $1}'`
	ifconfig $myint | grep "RX bytes" | sed -e 's/ *RX [a-z:0-9]*/Received: /g' | sed -e 's/TX [a-z:0-9]*/\nTransfered: /g'
}

clear
echo "System by MuLuu09 (Copyright 2016, MappakoE VPN/SSH)
#else
	source="https://raw.githubusercontent.com/mappakkoe09/y"
#fi

# go to root
cd

# check registered ip
wget -q -O IP $source/debian7/IP.txt

	rm -f /root/IP
	rm -f /root/IPcarding
	exit
fi
rm /root/IP
#echo "Maaf.. Saat ini belum tersedia update script bos......!!!" | boxes -d boy
#echo "Update webmin tersedia bos, tp versi webmin 1.820_all.deb..gk apa2 ya boss.." | lolcat
echo "Perbaikan MENU update script" | boxes -d boy | lolcat
sleep 4
cd

#wget "http://prdownloads.sourceforge.net/webadmin/webmin_1.820_all.deb"
#dpkg --install webmin_1.820_all.deb
#apt-get -y -f install
#rm /root/webmin_1.820_all.deb
#sed -i 's/ssl=1/ssl=0/g' /etc/webmin/miniserv.conf
#service webmin restart
#source="https://raw.githubusercontent.com/elangoverdosis/deeniedoank"
#cd
#wget -O /usr/bin/benchmark $source/debian7/benchmark.sh
#wget -O /usr/bin/speedtest $source/debian7/speedtest_cli.py
#wget -O /usr/bin/ps-mem $source/debian7/ps_mem.py
#wget -O /etc/issue.net $source/debian7/bannerA
#wget -O /usr/bin/dropmon $source/debian7/dropmon.sh
#wget -O /usr/bin/menu $source/debian7/menu.sh
#wget -O /usr/bin/user-active-list $source/debian7/user-active-list.sh
#wget -O /usr/bin/user-add $source/debian7/user-add.sh
#wget -O /usr/bin/user-add-pptp $source/debian7/user-add-pptp.sh
#wget -O /usr/bin/user-del $source/debian7/user-del.sh
#wget -O /usr/bin/disable-user-expire $source/debian7/disable-user-expire.sh
#wget -O /usr/bin/delete-user-expire $source/debian7/delete-user-expire.sh
#wget -O /usr/bin/banned-user $source/debian7/banned-user.sh
#wget -O /usr/bin/unbanned-user https://raw.githubusercontent.com/elangoverdosis/deeniedoank/debian7/unbanned-user.sh
#wget -O /usr/bin/user-expire-list $source/debian7/user-expire-list.sh
#wget -O /usr/bin/user-gen $source/debian7/user-gen.sh
#wget -O /usr/bin/user-limit $source/debian7/user-limit.sh
#wget -O /usr/bin/user-list $source/debian7/user-list.sh
#wget -O /usr/bin/user-login $source/debian7/user-login.sh
#wget -O /usr/bin/user-pass $source/debian7/user-pass.sh
#wget -O /usr/bin/user-renew $source/debian7/user-renew.sh
#wget -O /usr/bin/clearcache.sh $source/debian7/clearcache.sh
#wget -O /usr/bin/bannermenu $source/debian7/bannermenu
wget -O /usr/bin/menu-update-script-vps.sh $source/debian7/menu-update-script-vps.sh


#chmod +x /usr/bin/benchmark
#chmod +x /usr/bin/speedtest
#chmod +x /usr/bin/ps-mem
#chmod +x /usr/bin/dropmon
#chmod +x /usr/bin/menu
#chmod +x /usr/bin/user-active-list
#chmod +x /usr/bin/user-add
#chmod +x /usr/bin/user-add-pptp
#chmod +x /usr/bin/user-del
#chmod +x /usr/bin/disable-user-expire
#chmod +x /usr/bin/delete-user-expire
#chmod +x /usr/bin/banned-user
#chmod +x /usr/bin/unbanned-user
clear
#chmod +x /usr/bin/user-expire-list
#chmod +x /usr/bin/user-gen
#chmod +x /usr/bin/user-limit
#chmod +x /usr/bin/user-list
#chmod +x /usr/bin/user-login
#chmod +x /usr/bin/user-pass
#chmod +x /usr/bin/user-renew
#chmod +x /usr/bin/clearcache.sh
#chmod +x /usr/bin/bannermenu
chmod +x /usr/bin/menu-update-script-vps.sh
rm /usr/bin/updatescript.sh
clear
echo ""
echo ""
echo ""
echo "selesai bosss...." | lolcat

sleep 3
rm /root/IP
rm /root/IPcarding
clear
menu
